export const GET_CURRENT_VIDEO_CLIPS = 'GET_CURRENT_VIDEO_CLIPS';
export const GET_CURRENT_CLIP = 'GET_CURRENT_CLIP';
export const SAVE_VIDEO_CLIP = 'SAVE_VIDEO_CLIP';
export const EDIT_VIDEO_CLIP = 'EDIT_VIDEO_CLIP';
export const DELETE_VIDEO_CLIP = 'DELETE_VIDEO_CLIP';
